# Generated by Django 2.2.5 on 2019-09-13 08:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField(null=True)),
                ('date_to', models.DateField(null=True)),
                ('status', models.IntegerField(choices=[(0, 'Approved'), (1, 'Rejected'), (2, 'Processing')], default=1)),
                ('reason', models.TextField(max_length=200)),
                ('time_received', models.DateTimeField(null=True)),
                ('time_approved', models.DateTimeField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete='cascade', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
